export const BOOK_SET = "kitab/set"
export const LIST_BOOKS_SET = "list_kitab/set"
export const STORE_SET = "store/set"
export const PROMO_SET = "promo/set"
export const CHANNEL_YOUTUBE_SET = "channel_youtube/set"
export const BOOKS_ID_SET = "channel_youtube/set"